// <auto-generated />
using System;
using ClubMed.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubMed.Migrations
{
    [DbContext(typeof(ClubMedDbContext))]
    partial class ClubMedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Activite", b =>
                {
                    b.Property<int>("ActiviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("act_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActiviteId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("act_description");

                    b.Property<int?>("PartenaireId")
                        .HasColumnType("integer")
                        .HasColumnName("act_idpartenaire");

                    b.Property<decimal>("PrixMin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("act_prixmin");

                    b.Property<string>("Titre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("act_titre");

                    b.HasKey("ActiviteId")
                        .HasName("pk_activite");

                    b.ToTable("t_e_activite_act", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ActiviteAdulte", b =>
                {
                    b.Property<int>("ActiAdulteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("aca_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActiAdulteId"));

                    b.Property<int>("ActiAdulteAgeMin")
                        .HasColumnType("integer")
                        .HasColumnName("aca_ageminimum");

                    b.Property<string>("ActiAdulteDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("aca_description");

                    b.Property<decimal>("ActiAdulteDuree")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("aca_duree");

                    b.Property<string>("ActiAdulteFrequence")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("aca_frequence");

                    b.Property<int>("ActiAdulteNumType")
                        .HasColumnType("integer")
                        .HasColumnName("aca_numtypeactivite");

                    b.Property<decimal>("ActiAdultePrixMin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("aca_prixmin");

                    b.Property<string>("ActiAdulteTitre")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("aca_titre");

                    b.HasKey("ActiAdulteId")
                        .HasName("pk_activiteadulte");

                    b.HasIndex("ActiAdulteNumType");

                    b.ToTable("t_e_activiteadulte_aca", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ActiviteEnfant", b =>
                {
                    b.Property<int>("ActiEnfantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ace_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActiEnfantId"));

                    b.Property<string>("ActiEnfantDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ace_description");

                    b.Property<string>("ActiEnfantDetail")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ace_detail");

                    b.Property<int>("ActiEnfantNumTranche")
                        .HasColumnType("integer")
                        .HasColumnName("ace_numtranche");

                    b.Property<decimal>("ActiEnfantPrixMin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ace_prixmin");

                    b.Property<string>("ActiEnfantTitre")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ace_titre");

                    b.HasKey("ActiEnfantId")
                        .HasName("pk_activiteenfant");

                    b.HasIndex("ActiEnfantNumTranche");

                    b.ToTable("t_e_activiteenfant_ace", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ActiviteReservation", b =>
                {
                    b.Property<int>("ResaNum")
                        .HasColumnType("integer")
                        .HasColumnName("rea_numreservation");

                    b.Property<int>("ActiId")
                        .HasColumnType("integer")
                        .HasColumnName("rea_idactivite");

                    b.Property<bool>("IsDispoConfirmee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("rea_disponibiliteconfirmee");

                    b.Property<DateTime?>("ResaDateEnvoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rea_dateenvoi");

                    b.Property<int>("ResaNbPersonnes")
                        .HasColumnType("integer")
                        .HasColumnName("rea_nbpersonnes");

                    b.Property<string>("ResaToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rea_token");

                    b.HasKey("ResaNum", "ActiId")
                        .HasName("pk_activitereservation");

                    b.ToTable("t_j_activitereservation_rea", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("NumAdresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_numadresse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumAdresse"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)")
                        .HasColumnName("adr_codepostal");

                    b.Property<string>("NomRue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("adr_nomrue");

                    b.Property<int>("NumRue")
                        .HasColumnType("integer")
                        .HasColumnName("adr_numrue");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("adr_pays");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("adr_ville");

                    b.HasKey("NumAdresse")
                        .HasName("pk_adresse");

                    b.ToTable("t_e_adresse_adr", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.AutreVoyageur", b =>
                {
                    b.Property<int>("AutreVoyageurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("auv_numvoyageur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AutreVoyageurId"));

                    b.Property<DateTime?>("AutreVoyageurDateNaissance")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auv_datenaissance");

                    b.Property<string>("AutreVoyageurGenre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("auv_genre");

                    b.Property<string>("AutreVoyageurNom")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("auv_nom");

                    b.Property<int>("AutreVoyageurNumResa")
                        .HasColumnType("integer")
                        .HasColumnName("auv_numreservation");

                    b.Property<string>("AutreVoyageurPrenom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("auv_prenom");

                    b.HasKey("AutreVoyageurId")
                        .HasName("pk_autrevoyageur");

                    b.HasIndex("AutreVoyageurNumResa");

                    b.ToTable("t_e_autrevoyageur_auv", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Avis", b =>
                {
                    b.Property<int>("NumAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("avi_numavis");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumAvis"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avi_commentaire");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clu_idclub");

                    b.Property<int>("Note")
                        .HasColumnType("integer")
                        .HasColumnName("avi_note");

                    b.Property<int>("NumClient")
                        .HasColumnType("integer")
                        .HasColumnName("cli_numclient");

                    b.Property<int>("NumReservation")
                        .HasColumnType("integer")
                        .HasColumnName("res_numreservation");

                    b.Property<string>("Reponse")
                        .HasColumnType("text")
                        .HasColumnName("avi_reponse");

                    b.Property<string>("Titre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("avi_titre");

                    b.HasKey("NumAvis")
                        .HasName("pk_avis");

                    b.HasIndex("IdClub");

                    b.HasIndex("NumClient");

                    b.ToTable("t_j_avis_avi", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Calendrier", b =>
                {
                    b.Property<DateTime>("CalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cal_date");

                    b.HasKey("CalDate")
                        .HasName("pk_calendrier");

                    b.ToTable("t_e_calendrier_cal", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("NumCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_numcategory");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumCategory"));

                    b.Property<string>("NomCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cat_nomcategory");

                    b.HasKey("NumCategory")
                        .HasName("pk_numcategory");

                    b.ToTable("t_e_categorie_cat", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.CategorieLocalisation", b =>
                {
                    b.Property<int>("NumCategory")
                        .HasColumnType("integer")
                        .HasColumnName("numcategory");

                    b.Property<int>("NumLocalisation")
                        .HasColumnType("integer")
                        .HasColumnName("numlocalisation");

                    b.HasKey("NumCategory", "NumLocalisation")
                        .HasName("pk_categorie_localisation");

                    b.HasIndex("NumLocalisation");

                    b.ToTable("t_e_categorielocalisation_clo", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.CategorieTypeClub", b =>
                {
                    b.Property<int>("NumCategory")
                        .HasColumnType("integer")
                        .HasColumnName("cat_numcategory");

                    b.Property<int>("NumType")
                        .HasColumnType("integer")
                        .HasColumnName("tcl_numtype");

                    b.HasKey("NumCategory", "NumType")
                        .HasName("pk_categorie_typeclub");

                    b.HasIndex("NumType");

                    b.ToTable("t_e_categorietypeclub_ctc", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Chambre", b =>
                {
                    b.Property<int>("NumChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cha_num");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumChambre"));

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("tch_id");

                    b.HasKey("NumChambre")
                        .HasName("pk_chambre");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("t_e_chambre_cha");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Client", b =>
                {
                    b.Property<int>("NumClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cli_numclient");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumClient"));

                    b.Property<bool?>("A2fActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cli_a2f_active");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("cli_datenaissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cli_email");

                    b.Property<string>("Genre")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cli_genre");

                    b.Property<string>("MotDePasseCrypter")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cli_motdepasse_crypter");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cli_nom");

                    b.Property<int?>("NumAdresse")
                        .HasColumnType("integer")
                        .HasColumnName("cli_numadresse");

                    b.Property<string>("PmLastFour")
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("cli_pm_last_four");

                    b.Property<string>("PmType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cli_pm_type");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cli_prenom");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("client")
                        .HasColumnName("cli_role");

                    b.Property<string>("StripeId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cli_stripe_id");

                    b.Property<string>("Telephone")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cli_telephone");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_trial_ends_at");

                    b.HasKey("NumClient")
                        .HasName("pk_client");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_client_email");

                    b.HasIndex("NumAdresse");

                    b.ToTable("t_e_client_cli", null, t =>
                        {
                            t.HasCheckConstraint("ck_email", "((cli_email)::text ~~ '%_@_%._%'::text)");
                        });
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Club", b =>
                {
                    b.Property<int>("IdClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClub"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("clu_description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("clu_email");

                    b.Property<string>("LienPdf")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("clu_lienpdf");

                    b.Property<decimal?>("NoteMoyenne")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("clu_notemoyenne");

                    b.Property<int?>("NumPays")
                        .HasColumnType("integer")
                        .HasColumnName("clu_numpays");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("clu_numphoto");

                    b.Property<string>("StatutMiseEnLigne")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EN_CREATION")
                        .HasColumnName("clu_statut_mise_en_ligne");

                    b.Property<string>("Titre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clu_titre");

                    b.HasKey("IdClub")
                        .HasName("pk_club");

                    b.HasIndex("NumPays");

                    b.ToTable("t_e_club_clu", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubActivite", b =>
                {
                    b.Property<int>("ClubId")
                        .HasColumnType("integer")
                        .HasColumnName("cla_idclub");

                    b.Property<int>("ActiviteId")
                        .HasColumnType("integer")
                        .HasColumnName("cla_idactivite");

                    b.HasKey("ClubId", "ActiviteId")
                        .HasName("pk_clubactivite");

                    b.ToTable("t_j_clubactivite_cla", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubCategorie", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clu_idclub");

                    b.Property<int>("NumCategory")
                        .HasColumnType("integer")
                        .HasColumnName("cat_numcategory");

                    b.HasKey("IdClub", "NumCategory")
                        .HasName("pk_club_categorie");

                    b.HasIndex("NumCategory");

                    b.ToTable("t_j_clubcategorie_cca", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubChambre", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clu_id");

                    b.Property<int>("NumChambre")
                        .HasColumnType("integer")
                        .HasColumnName("cha_num");

                    b.HasKey("IdClub", "NumChambre")
                        .HasName("pk_club_chambre");

                    b.HasIndex("NumChambre");

                    b.ToTable("t_j_clubchambre_cch");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubRegroupement", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("crg_idclub");

                    b.Property<int>("NumRegroupement")
                        .HasColumnType("integer")
                        .HasColumnName("crg_numregroupement");

                    b.HasKey("IdClub", "NumRegroupement")
                        .HasName("pk_club_regroupement");

                    b.HasIndex("NumRegroupement");

                    b.ToTable("t_j_clubregroupement_crg", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubRestauration", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clu_idclub");

                    b.Property<int>("NumRestauration")
                        .HasColumnType("integer")
                        .HasColumnName("lre_numrestauration");

                    b.HasKey("IdClub", "NumRestauration")
                        .HasName("pk_club_lieurestuaration");

                    b.HasIndex("NumRestauration");

                    b.ToTable("t_j_clubrestauration_cre", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubStation", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clu_id");

                    b.Property<int>("IdStation")
                        .HasColumnType("integer")
                        .HasColumnName("sta_id");

                    b.Property<string>("AltitudeClub")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("clu_altitudeclub");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clu_description");

                    b.Property<string>("LienPdf")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("clu_lienpdf");

                    b.Property<decimal>("NoteMoyenne")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("clu_notemoyenne");

                    b.Property<int?>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("clu_numphoto");

                    b.Property<string>("Titre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clu_titre");

                    b.HasKey("IdClub", "IdStation")
                        .HasName("pk_club_station");

                    b.HasIndex("IdStation");

                    b.ToTable("t_j_clubstation_clu", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Disponibilite", b =>
                {
                    b.Property<DateTime>("DispoDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dis_date");

                    b.Property<int>("DispoNumChambre")
                        .HasColumnType("integer")
                        .HasColumnName("dis_numchambre");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer")
                        .HasColumnName("dis_idclub");

                    b.Property<bool?>("IsDisponible")
                        .HasColumnType("boolean")
                        .HasColumnName("dis_estdisponibilite");

                    b.HasKey("DispoDate", "DispoNumChambre", "ClubId")
                        .HasName("pk_disponibilite");

                    b.ToTable("t_e_disponibilite_dis", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Equipement", b =>
                {
                    b.Property<int>("NumEquipement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("equ_num");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumEquipement"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("equ_nom");

                    b.Property<int>("NumIcon")
                        .HasColumnType("integer")
                        .HasColumnName("icn_num");

                    b.HasKey("NumEquipement")
                        .HasName("pk_equipement");

                    b.HasIndex("NumIcon");

                    b.ToTable("t_e_equipement_equ");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.EquipementSalleDeBain", b =>
                {
                    b.Property<int>("NumEquipementSalleDeBain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("esb_num");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumEquipementSalleDeBain"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("esb_nom");

                    b.HasKey("NumEquipementSalleDeBain")
                        .HasName("pk_equipementsalledebain");

                    b.ToTable("t_e_equipementsalledebain_esb");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Icon", b =>
                {
                    b.Property<int>("NumIcon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ico_num");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumIcon"));

                    b.Property<string>("LienIcon")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ico_lien");

                    b.Property<int>("NumEquipementSalleDeBain")
                        .HasColumnType("integer")
                        .HasColumnName("esb_num");

                    b.Property<int>("NumPointFort")
                        .HasColumnType("integer")
                        .HasColumnName("ptf_num");

                    b.Property<int>("NumService")
                        .HasColumnType("integer")
                        .HasColumnName("srv_num");

                    b.HasKey("NumIcon")
                        .HasName("pk_icon");

                    b.HasIndex("NumEquipementSalleDeBain");

                    b.HasIndex("NumPointFort");

                    b.HasIndex("NumService");

                    b.ToTable("t_e_icon_ico");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.LieuRestauration", b =>
                {
                    b.Property<int>("NumRestauration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lre_numrestauration");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumRestauration"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lre_description");

                    b.Property<bool?>("EstBar")
                        .HasColumnType("boolean")
                        .HasColumnName("lre_estbar");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lre_nom");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("lre_numphoto");

                    b.Property<string>("Presentation")
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("lre_presentation");

                    b.HasKey("NumRestauration")
                        .HasName("PK_lre_numrestauration");

                    b.ToTable("t_e_lieurestauration_lre", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Localisation", b =>
                {
                    b.Property<int>("NumLocalisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("loc_numlocalisation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumLocalisation"));

                    b.Property<string>("NomLocalisation")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("loc_nomlocalisation");

                    b.HasKey("NumLocalisation")
                        .HasName("pk_localisation");

                    b.ToTable("t_r_localisation_loc", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Partenaire", b =>
                {
                    b.Property<int>("PartenaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("par_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartenaireId"));

                    b.Property<string>("PartenaireEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("par_email");

                    b.Property<string>("PartenaireNom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("par_nom");

                    b.Property<string>("PartenaireTelephone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("par_telephone");

                    b.HasKey("PartenaireId")
                        .HasName("pk_partenaire");

                    b.ToTable("t_e_partenaire_par", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PaysRegion", b =>
                {
                    b.Property<int>("NumLocalisation")
                        .HasColumnType("integer")
                        .HasColumnName("pyr_numlocalisation");

                    b.Property<int>("NumPays")
                        .HasColumnType("integer")
                        .HasColumnName("pyr_numpays");

                    b.HasKey("NumLocalisation", "NumPays")
                        .HasName("pk_pays_region");

                    b.HasIndex("NumPays");

                    b.ToTable("t_j_paysregion_pyr", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Periode", b =>
                {
                    b.Property<string>("NumPeriode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("per_num");

                    b.Property<DateTime?>("DateDeb")
                        .HasColumnType("date")
                        .HasColumnName("per_datedeb");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("date")
                        .HasColumnName("per_datefin");

                    b.HasKey("NumPeriode")
                        .HasName("pk_periode");

                    b.ToTable("t_e_periode_per");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Photo", b =>
                {
                    b.Property<int>("NumPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pho_numphoto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumPhoto"));

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("pho_url");

                    b.HasKey("NumPhoto")
                        .HasName("pho_numphoto");

                    b.ToTable("t_e_photo_pho", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PhotoAvis", b =>
                {
                    b.Property<int>("NumAvis")
                        .HasColumnType("integer")
                        .HasColumnName("avi_numavis");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("pho_numphoto");

                    b.HasKey("NumAvis", "NumPhoto")
                        .HasName("pk_avis_photo");

                    b.HasIndex("NumPhoto");

                    b.ToTable("t_j_photo_avis_pav", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PhotoClub", b =>
                {
                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clu_idclub");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("pho_numphoto");

                    b.Property<int?>("Ordre")
                        .HasColumnType("integer")
                        .HasColumnName("pcl_ordre");

                    b.HasKey("IdClub", "NumPhoto")
                        .HasName("pk_club_photo");

                    b.HasIndex("NumPhoto");

                    b.ToTable("t_j_photo_club_pcl", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PointFort", b =>
                {
                    b.Property<int>("NumPointFort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ptf_numpointfort");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumPointFort"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ptf_nom");

                    b.HasKey("NumPointFort")
                        .HasName("pk_pointfort");

                    b.ToTable("t_e_pointfort_ptf");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PrixPeriode", b =>
                {
                    b.Property<string>("NumPeriode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("per_num");

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("tch_id");

                    b.Property<decimal?>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric")
                        .HasColumnName("prp_prixperiode");

                    b.HasKey("NumPeriode", "IdTypeChambre")
                        .HasName("pk_prix_periode");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("t_j_prixperiode_prp");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Regroupement", b =>
                {
                    b.Property<int>("NumRegroupement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rgr_numregroupement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumRegroupement"));

                    b.Property<string>("LibelleRegroupement")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("rgr_libelleregroupement");

                    b.HasKey("NumRegroupement")
                        .HasName("pk_regroupement");

                    b.ToTable("t_r_regroupement_rgr", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Reservation", b =>
                {
                    b.Property<int>("ResaNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("res_numreservation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResaNum"));

                    b.Property<int>("ClientNum")
                        .HasColumnType("integer")
                        .HasColumnName("res_numclient");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer")
                        .HasColumnName("res_idclub");

                    b.Property<bool?>("IsDemandeAnnulation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("res_veutannuler");

                    b.Property<bool?>("IsDispoConfirmee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("res_disponibiliteconfirmee");

                    b.Property<bool?>("IsMailConfirmeEnvoye")
                        .HasColumnType("boolean")
                        .HasColumnName("res_mailconfirmationenvoye");

                    b.Property<DateTime?>("ResaDateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("res_datedebut");

                    b.Property<DateTime?>("ResaDateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("res_datefin");

                    b.Property<string>("ResaEtatCalcule")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("res_etatcalcule");

                    b.Property<string>("ResaLieuDepart")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("res_lieudepart");

                    b.Property<bool?>("ResaMailEnvoye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("res_mail");

                    b.Property<int?>("ResaNbPersonnes")
                        .HasColumnType("integer")
                        .HasColumnName("res_nbpersonnes");

                    b.Property<decimal?>("ResaPrix")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("res_prix");

                    b.Property<string>("ResaStatut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EN_ATTENTE")
                        .HasColumnName("res_statut");

                    b.Property<int>("TransportId")
                        .HasColumnType("integer")
                        .HasColumnName("res_idtransport");

                    b.HasKey("ResaNum")
                        .HasName("pk_reservation");

                    b.HasIndex("TransportId");

                    b.ToTable("t_e_reservation_res", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Service", b =>
                {
                    b.Property<int>("NumService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("srv_num");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumService"));

                    b.Property<string>("Nom")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("srv_nom");

                    b.HasKey("NumService")
                        .HasName("pk_service");

                    b.ToTable("t_e_service_srv");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.SousLocalisation", b =>
                {
                    b.Property<int>("NumPays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("slc_numpays");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumPays"));

                    b.Property<string>("NomPays")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("slc_nompays");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("slc_numphoto");

                    b.HasKey("NumPays")
                        .HasName("pk_souslocalisation");

                    b.ToTable("t_r_souslocalisation_slc", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Station", b =>
                {
                    b.Property<int>("IdStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStation"));

                    b.Property<decimal>("AltitudeStation")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sta_altitudestation");

                    b.Property<string>("InfoSki")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sta_infoski");

                    b.Property<decimal>("LongueurPistes")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sta_longueurpistes");

                    b.Property<int>("NbPistes")
                        .HasColumnType("integer")
                        .HasColumnName("sta_nbpistes");

                    b.Property<string>("NomStation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("sta_nomstation");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("sta_numphoto");

                    b.HasKey("IdStation")
                        .HasName("pk_station");

                    b.ToTable("t_e_station_sta", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TrancheAge", b =>
                {
                    b.Property<int>("TrancheNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tra_numtranche");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrancheNum"));

                    b.Property<int?>("TrancheAgeMax")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("tra_agemax");

                    b.Property<int?>("TrancheAgeMin")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("tra_agemin");

                    b.HasKey("TrancheNum")
                        .HasName("pk_trancheage");

                    b.ToTable("t_e_trancheage_tra", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trs_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("ResaNum")
                        .HasColumnType("integer")
                        .HasColumnName("trs_numreservation");

                    b.Property<DateTime?>("TransactionDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trs_datetransaction")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("TransactionMontant")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("trs_montant");

                    b.Property<string>("TransactionMoyenPaiement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trs_moyenpaiement");

                    b.Property<string>("TransactionStatut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trs_statutpaiement");

                    b.HasKey("TransactionId")
                        .HasName("pk_transaction");

                    b.HasIndex("ResaNum");

                    b.ToTable("t_e_transaction_trs", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Transport", b =>
                {
                    b.Property<int>("TransportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tra_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransportId"));

                    b.Property<string>("TransportLieuDepart")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("tra_lieudepart");

                    b.Property<decimal?>("TransportPrix")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tra_prix");

                    b.HasKey("TransportId")
                        .HasName("pk_transport");

                    b.ToTable("t_e_transport_tra", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeActivite", b =>
                {
                    b.Property<int>("TypeActiviteNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tya_numtypeactivite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeActiviteNum"));

                    b.Property<string>("TypeActiviteDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("tya_description");

                    b.Property<int>("TypeActiviteNbCarte")
                        .HasColumnType("integer")
                        .HasColumnName("tya_nbactivitecarte");

                    b.Property<int>("TypeActiviteNbIncluse")
                        .HasColumnType("integer")
                        .HasColumnName("tya_nbactiviteincluse");

                    b.Property<int>("TypeActiviteNumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("tya_numphoto");

                    b.Property<string>("TypeActiviteTitre")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("tya_titre");

                    b.HasKey("TypeActiviteNum")
                        .HasName("pk_typeactivite");

                    b.ToTable("t_e_typeactivite_tya", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambre", b =>
                {
                    b.Property<int>("IdTypeChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tch_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTypeChambre"));

                    b.Property<int?>("CapaciteMax")
                        .HasColumnType("integer")
                        .HasColumnName("tch_capacitemax");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer")
                        .HasColumnName("clu_id");

                    b.Property<bool?>("Indisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tch_indisponible");

                    b.Property<string>("NomType")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("tch_nom");

                    b.Property<int>("NumPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("pht_id");

                    b.Property<double?>("Surface")
                        .HasColumnType("double precision")
                        .HasColumnName("tch_surface");

                    b.Property<string>("TextePresentation")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("tch_textepresentation");

                    b.HasKey("IdTypeChambre")
                        .HasName("pk_typechambre");

                    b.HasIndex("IdClub");

                    b.HasIndex("NumPhoto");

                    b.ToTable("t_e_typechambre_tch");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambreEquipement", b =>
                {
                    b.Property<int>("NumEquipement")
                        .HasColumnType("integer")
                        .HasColumnName("equ_numequipement");

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("tch_id");

                    b.HasKey("NumEquipement", "IdTypeChambre")
                        .HasName("pk_type_chambre_equipement");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("t_j_typechambreequipement_tce");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambrePointFort", b =>
                {
                    b.Property<int>("NumPointFort")
                        .HasColumnType("integer")
                        .HasColumnName("numpointfort");

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("idtypechambre");

                    b.HasKey("NumPointFort", "IdTypeChambre")
                        .HasName("pk_type_chambre_pointfort");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("t_j_typechambrepointfort_tpf");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambreSdb", b =>
                {
                    b.Property<int>("NumEquipementSalleDeBain")
                        .HasColumnType("integer")
                        .HasColumnName("esb_num");

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("tch_id");

                    b.HasKey("NumEquipementSalleDeBain", "IdTypeChambre")
                        .HasName("pk_type_chambre_sdb");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("t_e_typechambresdb_tcs");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambreService", b =>
                {
                    b.Property<int>("NumService")
                        .HasColumnType("integer")
                        .HasColumnName("numservice");

                    b.Property<int>("IdTypeChambre")
                        .HasColumnType("integer")
                        .HasColumnName("idtypechambre");

                    b.HasKey("NumService", "IdTypeChambre")
                        .HasName("pk_type_chambre_service");

                    b.HasIndex("IdTypeChambre");

                    b.ToTable("t_j_typechambreservice_tcr");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeClub", b =>
                {
                    b.Property<int>("NumType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tcl_numtype");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumType"));

                    b.Property<string>("NomType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tcl_nomtype");

                    b.HasKey("NumType")
                        .HasName("pk_typeclub");

                    b.ToTable("t_e_typeclub_tcl", (string)null);
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ActiviteAdulte", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TypeActivite", "TypeActivite")
                        .WithMany("ActivitesAdultes")
                        .HasForeignKey("ActiAdulteNumType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activiteadulte_typeactivite");

                    b.Navigation("TypeActivite");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ActiviteEnfant", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TrancheAge", "TrancheAge")
                        .WithMany("ActivitesEnfants")
                        .HasForeignKey("ActiEnfantNumTranche")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activiteenfant_trancheage");

                    b.Navigation("TrancheAge");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ActiviteReservation", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Reservation", "Reservation")
                        .WithMany("ActivitesReservations")
                        .HasForeignKey("ResaNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activitereservation_reservation");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.AutreVoyageur", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Reservation", "Reservation")
                        .WithMany("AutresVoyageurs")
                        .HasForeignKey("AutreVoyageurNumResa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_autrevoyageur_reservation");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Avis", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "Club")
                        .WithMany("Avis")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avis_club");

                    b.HasOne("ClubMed.Models.EntityFramework.Client", "Client")
                        .WithMany("Avis")
                        .HasForeignKey("NumClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avis_client");

                    b.Navigation("Client");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.CategorieLocalisation", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Categorie", "Categorie")
                        .WithMany("CategorieLocalisations")
                        .HasForeignKey("NumCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorie_localisation_category");

                    b.HasOne("ClubMed.Models.EntityFramework.Localisation", "Localisation")
                        .WithMany("CategorieLocalisations")
                        .HasForeignKey("NumLocalisation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorie_localisation_localisation");

                    b.Navigation("Categorie");

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.CategorieTypeClub", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Categorie", "Categorie")
                        .WithMany("CategorieTypeClubs")
                        .HasForeignKey("NumCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorie_typeclub_category");

                    b.HasOne("ClubMed.Models.EntityFramework.TypeClub", "TypeClub")
                        .WithMany("CategorieTypeClubs")
                        .HasForeignKey("NumType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorie_typeclub_typeclub");

                    b.Navigation("Categorie");

                    b.Navigation("TypeClub");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Chambre", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TypeChambre", "Type")
                        .WithMany("Chambres")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chambre_typechambre");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Client", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Adresse", "AdresseResidence")
                        .WithMany("Clients")
                        .HasForeignKey("NumAdresse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_client_adresse");

                    b.Navigation("AdresseResidence");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Club", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.SousLocalisation", "SousLocalisation")
                        .WithMany("Clubs")
                        .HasForeignKey("NumPays")
                        .HasConstraintName("fk_club_souslocalisation");

                    b.Navigation("SousLocalisation");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubCategorie", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "Club")
                        .WithMany("ClubCategories")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMed.Models.EntityFramework.Categorie", "Categorie")
                        .WithMany("ClubCategories")
                        .HasForeignKey("NumCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubChambre", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "Club")
                        .WithMany("ClubChambres")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clubchambre_club");

                    b.HasOne("ClubMed.Models.EntityFramework.Chambre", "Chambre")
                        .WithMany("ClubChambres")
                        .HasForeignKey("NumChambre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clubchambre_chambre");

                    b.Navigation("Chambre");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubRegroupement", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "ClubAssocie")
                        .WithMany("ClubRegroupements")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crg_clb");

                    b.HasOne("ClubMed.Models.EntityFramework.Regroupement", "RegroupementAssocie")
                        .WithMany("ClubRegroupements")
                        .HasForeignKey("NumRegroupement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crg_rgr");

                    b.Navigation("ClubAssocie");

                    b.Navigation("RegroupementAssocie");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubRestauration", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "Club")
                        .WithMany("ClubRestaurations")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clubrestauration_club");

                    b.HasOne("ClubMed.Models.EntityFramework.LieuRestauration", "LieuRestauration")
                        .WithMany("ClubRestaurations")
                        .HasForeignKey("NumRestauration")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clubrestauration_lieurestauration");

                    b.Navigation("Club");

                    b.Navigation("LieuRestauration");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.ClubStation", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "Club")
                        .WithMany("ClubStations")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clubstation_club");

                    b.HasOne("ClubMed.Models.EntityFramework.Station", "Station")
                        .WithMany("ClubStations")
                        .HasForeignKey("IdStation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clubstation_station");

                    b.Navigation("Club");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Disponibilite", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Calendrier", "Calendrier")
                        .WithMany("Disponibilites")
                        .HasForeignKey("DispoDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disponibilite_calendrier");

                    b.Navigation("Calendrier");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Equipement", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Icon", "Icon")
                        .WithMany("Equipements")
                        .HasForeignKey("NumIcon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipement_icon");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Icon", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.EquipementSalleDeBain", "EquipementSalleDeBainNav")
                        .WithMany("Icons")
                        .HasForeignKey("NumEquipementSalleDeBain")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_icon_equipementsalledebain");

                    b.HasOne("ClubMed.Models.EntityFramework.PointFort", "PointFortNav")
                        .WithMany("Icons")
                        .HasForeignKey("NumPointFort")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_icon_pointfort");

                    b.HasOne("ClubMed.Models.EntityFramework.Service", "ServiceNav")
                        .WithMany("Icons")
                        .HasForeignKey("NumService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_icon_service");

                    b.Navigation("EquipementSalleDeBainNav");

                    b.Navigation("PointFortNav");

                    b.Navigation("ServiceNav");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PaysRegion", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Localisation", "LocalisationAssociee")
                        .WithMany("PaysRegions")
                        .HasForeignKey("NumLocalisation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pyr_loc");

                    b.HasOne("ClubMed.Models.EntityFramework.SousLocalisation", "SousLocalisationAssociee")
                        .WithMany("PaysRegions")
                        .HasForeignKey("NumPays")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pyr_slc");

                    b.Navigation("LocalisationAssociee");

                    b.Navigation("SousLocalisationAssociee");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PhotoAvis", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Avis", "Avis")
                        .WithMany("PhotoAvis")
                        .HasForeignKey("NumAvis")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubMed.Models.EntityFramework.Photo", "Photo")
                        .WithMany("PhotoAvis")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avis");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PhotoClub", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "Club")
                        .WithMany("PhotoClubs")
                        .HasForeignKey("IdClub")
                        .IsRequired()
                        .HasConstraintName("fk_club_photo_club");

                    b.HasOne("ClubMed.Models.EntityFramework.Photo", "Photo")
                        .WithMany("PhotoClubs")
                        .HasForeignKey("NumPhoto")
                        .IsRequired()
                        .HasConstraintName("fk_club_photo_photo");

                    b.Navigation("Club");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PrixPeriode", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TypeChambre", "TypeChambreNav")
                        .WithMany("PrixPeriodes")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prix_periode_typechambre");

                    b.HasOne("ClubMed.Models.EntityFramework.Periode", "Periode")
                        .WithMany("PrixPeriodes")
                        .HasForeignKey("NumPeriode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prix_periode_periode");

                    b.Navigation("Periode");

                    b.Navigation("TypeChambreNav");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Reservation", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Transport", "Transport")
                        .WithMany("Reservations")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_transport");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Transaction", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Reservation", "Reservation")
                        .WithMany("Transactions")
                        .HasForeignKey("ResaNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_reservation");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambre", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.Club", "ClubNav")
                        .WithMany("TypeChambres")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_club_typechambre");

                    b.HasOne("ClubMed.Models.EntityFramework.Photo", "PhotoNav")
                        .WithMany("TypeChambres")
                        .HasForeignKey("NumPhoto")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_typechambre_photo");

                    b.Navigation("ClubNav");

                    b.Navigation("PhotoNav");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambreEquipement", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TypeChambre", "TypeChambreNav")
                        .WithMany("TypeChambreEquipements")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_equipement_typechambre");

                    b.HasOne("ClubMed.Models.EntityFramework.Equipement", "EquipementNav")
                        .WithMany("TypeChambreEquipements")
                        .HasForeignKey("NumEquipement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_equipement_equipement");

                    b.Navigation("EquipementNav");

                    b.Navigation("TypeChambreNav");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambrePointFort", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TypeChambre", "TypeChambreNav")
                        .WithMany("TypeChambrePointForts")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_pointfort_typechambre");

                    b.HasOne("ClubMed.Models.EntityFramework.PointFort", "PointFortNav")
                        .WithMany("TypeChambrePointForts")
                        .HasForeignKey("NumPointFort")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_pointfort_pointfort");

                    b.Navigation("PointFortNav");

                    b.Navigation("TypeChambreNav");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambreSdb", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TypeChambre", "TypeChambreNav")
                        .WithMany("TypeChambreSdbs")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_sdb_typechambre");

                    b.HasOne("ClubMed.Models.EntityFramework.EquipementSalleDeBain", "EquipementSalleDeBainNav")
                        .WithMany("TypeChambreSdbs")
                        .HasForeignKey("NumEquipementSalleDeBain")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_sdb_equipementsalledebain");

                    b.Navigation("EquipementSalleDeBainNav");

                    b.Navigation("TypeChambreNav");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambreService", b =>
                {
                    b.HasOne("ClubMed.Models.EntityFramework.TypeChambre", "TypeChambreNav")
                        .WithMany("TypeChambreServices")
                        .HasForeignKey("IdTypeChambre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_service_typechambre");

                    b.HasOne("ClubMed.Models.EntityFramework.Service", "ServiceNav")
                        .WithMany("TypeChambreServices")
                        .HasForeignKey("NumService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_type_chambre_service_service");

                    b.Navigation("ServiceNav");

                    b.Navigation("TypeChambreNav");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Avis", b =>
                {
                    b.Navigation("PhotoAvis");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Calendrier", b =>
                {
                    b.Navigation("Disponibilites");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Categorie", b =>
                {
                    b.Navigation("CategorieLocalisations");

                    b.Navigation("CategorieTypeClubs");

                    b.Navigation("ClubCategories");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Chambre", b =>
                {
                    b.Navigation("ClubChambres");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Client", b =>
                {
                    b.Navigation("Avis");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Club", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("ClubCategories");

                    b.Navigation("ClubChambres");

                    b.Navigation("ClubRegroupements");

                    b.Navigation("ClubRestaurations");

                    b.Navigation("ClubStations");

                    b.Navigation("PhotoClubs");

                    b.Navigation("TypeChambres");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Equipement", b =>
                {
                    b.Navigation("TypeChambreEquipements");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.EquipementSalleDeBain", b =>
                {
                    b.Navigation("Icons");

                    b.Navigation("TypeChambreSdbs");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Icon", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.LieuRestauration", b =>
                {
                    b.Navigation("ClubRestaurations");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Localisation", b =>
                {
                    b.Navigation("CategorieLocalisations");

                    b.Navigation("PaysRegions");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Periode", b =>
                {
                    b.Navigation("PrixPeriodes");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Photo", b =>
                {
                    b.Navigation("PhotoAvis");

                    b.Navigation("PhotoClubs");

                    b.Navigation("TypeChambres");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.PointFort", b =>
                {
                    b.Navigation("Icons");

                    b.Navigation("TypeChambrePointForts");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Regroupement", b =>
                {
                    b.Navigation("ClubRegroupements");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Reservation", b =>
                {
                    b.Navigation("ActivitesReservations");

                    b.Navigation("AutresVoyageurs");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Service", b =>
                {
                    b.Navigation("Icons");

                    b.Navigation("TypeChambreServices");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.SousLocalisation", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("PaysRegions");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Station", b =>
                {
                    b.Navigation("ClubStations");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TrancheAge", b =>
                {
                    b.Navigation("ActivitesEnfants");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.Transport", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeActivite", b =>
                {
                    b.Navigation("ActivitesAdultes");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeChambre", b =>
                {
                    b.Navigation("Chambres");

                    b.Navigation("PrixPeriodes");

                    b.Navigation("TypeChambreEquipements");

                    b.Navigation("TypeChambrePointForts");

                    b.Navigation("TypeChambreSdbs");

                    b.Navigation("TypeChambreServices");
                });

            modelBuilder.Entity("ClubMed.Models.EntityFramework.TypeClub", b =>
                {
                    b.Navigation("CategorieTypeClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
